encoder: masking-model
encoder_args:
  encoder: resnet12
  encoder_args: {avg_pool: false, drop_rate: 0.1, dropblock_size: 5}
  masking: multi-block-masking
  masking_args: {channels: [640, 320, 1], final_relu: False, max_pool: False, activation: sigmoid, drop_rate: 0.1, dropblock_size: 5}
